"App: Data Importer": "apps/data-importer/**/*"
"App: Invoices": "apps/invoices/**/*"
"App: Klaviyo": "apps/klaviyo/**/*"
"App: Monitoring": "apps/monitoring/**/*"
"App: Product Feed": "apps/products-feed/**/*"
"App: Search": "apps/search/**/*"
"App: Slack": "apps/slack/**/*"
"App: Taxes": "apps/taxes/**/*"
"App: Emails & Messages": "apps/emails-and-messages/**/*"
"App: CMS": "apps/cms/**/*"
"App: CRM": "apps/crm/**/*"
